### PR TITLE
[CK_TILE] Fix fMHA fwd MakeKargs() compilation errors

### PR DESCRIPTION
**Pull request by poyenc**
This is follow-up PR of #1638, fix errors introduced in #1681

- Rename `std::variant<>` version `MakeKargs()` as `MakeKargsImpl()` (prevent ambiguity if user calls `MakeKargs()` and pass list initializer argument)
- Add missing `return` in `MakeKargs()`
- Replace `__host__` with `CK_TILE_HOST` macros

### CODE REVIEW

**Comment by poyenc** [comment]
fix errors which was introduced in #1681

**Review by qianfengz — APPROVED** [review]
