### PR TITLE
remove gfx12 targets from daily builds with rocm6.2

### PR DESCRIPTION
**Pull request by illsilin**
rocm6.2 does not fully support gfx12 targets, which causes compilation errors.

### CODE REVIEW

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@illsilin why not let the logic handle it instead of listing it our explicitly?

https://github.com/ROCm/composable_kernel/blob/ceaed8e097cbba105e23f465c6226ab48e37a3a8/CMakeLists.txt#L148-L154
