### PR TITLE
[CK_TILE] MUST USE INLINE FOR ANY NON TEMPLATE FUNCTION IN HEADER

### PR DESCRIPTION
**Pull request by carlushuang**
introduced in https://github.com/ROCm/composable_kernel/pull/2284 Now any ck-tile example will result in duplicated symbol error, like below:
```
/opt/rocm/lib/libamdhip64.so.6.3.60301 --hip-link --offload-arch=gfx942 /opt/rocm-6.3.1/lib/llvm/lib/clang/18/lib/linux/libclang_rt.builtins-x86_64.a
ld.lld: error: duplicate symbol: ck_tile::report_error_stats(int, double, unsigned long)
>>> defined at moe_sorting.cpp
>>>            CMakeFiles/tile_example_moe_sorting.dir/moe_sorting.cpp.o:(ck_tile::report_error_stats(int, double, unsigned long))
>>> defined at moe_sorting_api.cpp
>>>            CMakeFiles/tile_example_moe_sorting.dir/moe_sorting_api.cpp.o:(.text+0x0)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
failed to execute:/opt/rocm/lib/llvm/bin/clang++ --driver-mode=g++ --hip-link  -std=c++17 -O3 -ftemplate-backtrace-limit=0 -fPIE -Wno-gnu-line-marker -O3 -DNDEBUG -Xlinker --dependency-file=CMakeFiles/tile_example_moe_sorting.dir/link.d CMakeFiles/tile_example_moe_sorting.dir/moe_sorting.cpp.o CMakeFiles/tile_example_moe_sorting.dir/moe_sorting_api.cpp.o -o "../../../bin/tile_example_moe_sorting" /opt/rocm/lib/libamdhip64.so.6.3.60301 --hip-link /opt/rocm-6.3.1/lib/llvm/lib/clang/
```

CK, as a header only library, must make sure we use `inline` for every function in header, especially for any non-template function. Otherwise will result in duplicated symbol if we include such function in multiple source file

### CODE REVIEW

**Review by asleepzzz — APPROVED** [review]

**Review by aosewski — APPROVED** [review]

**Comment by aosewski** [comment]
Let's wait for CI to finish and we can merge it.

File: include/ck_tile/host/check_err.hpp [hunk 1]
```diff
@@ -46,7 +46,7 @@ using I32 = int32_t;
  * @return Relative error threshold based on data type characteristics
  */
 template <typename ComputeDataType, typename OutDataType, typename AccDataType = ComputeDataType>
-double get_relative_threshold(const int number_of_accumulations = 1)
+CK_TILE_HOST double get_relative_threshold(const int number_of_accumulations = 1)
```
Comment (AviralGoelAMD) [inline include/ck_tile/host/check_err.hpp:49]: Do we also need to do inline for templated functions?

Comment (AviralGoelAMD) [reply include/ck_tile/host/check_err.hpp:49]: @carlushuang, I just wondering if we NEED to do it or are we doing it for templated functions for consistency?
